version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=bora_uber_clone_secret_2024
      - PORT=5000
    restart: always
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_GOOGLE_MAPS_API_KEY=AIzaSyAVe7W-B0zZa-6ePrcLfZkDzs1RGRSHSCc
      - FAST_REFRESH=false
      - BROWSER=none
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 