services:
  - type: web
    name: leva-backend
    env: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://ara100limite:ERxkG9nXZjbwvpMk@cluster0.yzf2r.mongodb.net/bora?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: bora_uber_clone_secret_2024
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "https://newrepo-woad-nine.vercel.app"
      - key: ALLOWED_ORIGINS
        value: "https://newrepo-woad-nine.vercel.app,http://localhost:3000" 